name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_STAGING_TOKEN }}
        working-directory: ./frontend
        env:
          VERCEL_ORG_ID: team_0GOp2dbTcdsl9NqDGhtIPY2N
          VERCEL_PROJECT_ID: prj_mQk4ClT5cVPRAcmEDigB3LBAb0Gl

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_STAGING_TOKEN }}
        working-directory: ./frontend
        env:
          VERCEL_ORG_ID: team_0GOp2dbTcdsl9NqDGhtIPY2N
          VERCEL_PROJECT_ID: prj_mQk4ClT5cVPRAcmEDigB3LBAb0Gl

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_STAGING_TOKEN }}
        working-directory: ./frontend
        env:
          VERCEL_ORG_ID: team_0GOp2dbTcdsl9NqDGhtIPY2N
          VERCEL_PROJECT_ID: prj_mQk4ClT5cVPRAcmEDigB3LBAb0Gl

      - name: Comment deployment URL
        if: success()
        run: |
          echo "âœ… Deployed to production: https://trapid.vercel.app"
